name: CI MLProject

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  train-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies (MLflow + libs)
        run: |
          python -m pip install --upgrade pip
          pip install mlflow==2.19.0 numpy pandas scikit-learn matplotlib seaborn dagshub joblib

      # === BASIC & SKILLED: jalankan MLflow Project ===
      - name: Run MLflow project
        run: |
          mlflow run MLProject --env-manager=local

      # === SKILLED: simpan artefak ke repositori (GitHub Artifacts) ===
      - name: Upload MLflow artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-artifacts
          path: mlruns

      - name: Upload exported model
        uses: actions/upload-artifact@v4
        with:
          name: exported-model
          path: MLProject/exported_model

      # === ADVANCED: build & push Docker image ke Docker Hub ===
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image with MLflow
        run: |
          IMAGE_NAME="${{ secrets.DOCKERHUB_USERNAME }}/heart-failure-model:latest"
          MODEL_PATH="${GITHUB_WORKSPACE}/MLProject/exported_model"
          echo "Model path: $MODEL_PATH"
          ls -R MLProject
          mlflow models build-docker -m "$MODEL_PATH" -n "$IMAGE_NAME" --enable-mlserver
          docker push "$IMAGE_NAME"
